// 자동 생성(gen_copy.py) — 직접 고치지 말고 marketing.py 를 고친다.
window.S = {
 "brand": "Anbu",
 "push_app": "Anbu",
 "dad": "Dad",
 "p8_lang": "20 languages",
 "p1_h": "Worried about <em>parents</em><br>living far away?",
 "p1_s": "A child living alone is on your mind too,<br>and calling every day isn’t easy.",
 "p2_h": "They always say “I’m fine,”<br>but are they really?",
 "p2_o": "That’s when you need Anbu.",
 "p2_s": "Without reaching out,<br>your family’s wellness check arrives automatically.",
 "bubble": "I’m fine, don’t worry~",
 "p3_h": "Without reaching out,<br>a <em>wellness check</em> arrives daily",
 "p3_s": "Wellness checks and steps arrive automatically.<br>The sender doesn’t even need to open the app.",
 "p4_h": "When contact stops,<br>you’re <em>the first to know</em>",
 "p4_s": "No wellness check? Caution → warning → urgent,<br>step by step.",
 "p5_h": "<em>One code</em><br>and you’re connected",
 "p5_s": "Enter your loved one’s code and a nickname<br>to start receiving their wellness checks.",
 "p6_h": "Your family’s wellness,<br><em>at a glance</em>",
 "p6_s": "Up to 5 people on one screen:<br>wellness checks and steps.",
 "p7_h": "When help is needed,<br><em>location</em> comes along",
 "p7_s": "When your loved one taps “I need help,” guardians are alerted right away — location is shared only then.",
 "p8_h": "<em>No sign-up</em><br>needed",
 "p8_s": "Names and phone numbers aren’t stored on our server.",
 "p8_chips": [
  "Name",
  "Phone number",
  "Address"
 ],
 "p8_loc": "Location only when “I need help” is tapped",
 "n_title": "Notifications",
 "n_today": "Today's notifications",
 "lv_normal": "Normal",
 "lv_caution": "Caution",
 "lv_warning": "Warning",
 "lv_urgent": "Urgent",
 "b_auto": "Your loved one's wellness check came in as usual.",
 "b_caution": "Today's scheduled wellness check hasn't arrived yet. Please check on them yourself.",
 "b_warning": "Wellness checks have been missed on consecutive days. Please check on them yourself.",
 "b_urgent": "No wellness check for 3 days. Please check on them right away.",
 "b_sos": "Your loved one has asked for help. Please check on them right away.",
 "view_loc": "🗺️ View location",
 "add_title": "Connect a loved one",
 "add_guide": "Enter the unique code and a nickname for the person you want to connect.",
 "add_sub": "Once connected, you can see their daily wellness check and step count.",
 "add_code_label": "Unique code (7 characters)",
 "add_alias_label": "Nickname",
 "add_phone_label": "Phone number (optional)",
 "add_phone_hint": "2015550123",
 "add_connect": "Connect",
 "add_ok": "Your loved one is now connected.",
 "d1_head": "Looking after<br>1 person right now.",
 "d3_head": "Looking after<br>3 people right now.",
 "legend_ok": "Safe: 2",
 "legend_caution": "Caution: 1",
 "pill_caution": "⚠️ Caution",
 "safety_needed": "Safety check needed",
 "call_now": "Call now",
 "confirm_safety": "Confirm safe",
 "last_1d": "Last check: 1 day ago",
 "last_3h": "Last check: 3 hr ago",
 "map_title": "Emergency location",
 "map_subject": "Loved one",
 "map_time": "Recorded at",
 "map_acc": "Accuracy"
};
