// 자동 생성(gen_copy.py) — 직접 고치지 말고 marketing.py 를 고친다.
window.S = {
 "brand": "Anbu",
 "push_app": "Anbu",
 "dad": "Papá",
 "p8_lang": "20 idiomas",
 "p1_h": "¿Le preocupan sus <em>padres</em><br>que viven lejos?",
 "p1_s": "También un hijo que vive solo le inquieta,<br>y llamar cada día no es fácil.",
 "p2_h": "Siempre dicen «estoy bien»,<br>pero ¿de verdad lo están?",
 "p2_o": "Para eso está Anbu.",
 "p2_s": "Sin que usted llame, el aviso de su familia<br>llega automáticamente cada día.",
 "bubble": "Estoy bien, no te preocupes~",
 "p3_h": "Sin llamar,<br>el <em>aviso</em> llega cada día",
 "p3_s": "El aviso y los pasos llegan solos.<br>Quien lo envía ni siquiera tiene que abrir la app.",
 "p4_h": "Si se corta el contacto,<br>usted lo sabe <em>antes que nadie</em>",
 "p4_s": "Si no llega el aviso: precaución → alerta → urgente,<br>paso a paso.",
 "p5_h": "<em>Un solo código</em><br>y ya está conectado",
 "p5_s": "Introduzca el código y el apodo de su ser querido<br>y reciba su aviso enseguida.",
 "p6_h": "El aviso de toda su familia,<br><em>de un vistazo</em>",
 "p6_s": "Hasta 5 personas en una pantalla:<br>aviso y pasos.",
 "p7_h": "Si necesita ayuda,<br>la <em>ubicación</em> va incluida",
 "p7_s": "Cuando su ser querido pulsa «Necesito ayuda», el cuidador recibe un aviso al instante; la ubicación solo se comparte entonces.",
 "p8_h": "<em>Sin registro</em><br>alguno",
 "p8_s": "Ni el nombre ni el teléfono se guardan en el servidor.",
 "p8_chips": [
  "Nombre",
  "Teléfono",
  "Dirección"
 ],
 "p8_loc": "Ubicación solo al pulsar «Necesito ayuda»",
 "n_title": "Notificaciones",
 "n_today": "Recibidas hoy",
 "lv_normal": "Normal",
 "lv_caution": "Precaución",
 "lv_warning": "Alerta",
 "lv_urgent": "Urgente",
 "b_auto": "El aviso de su ser querido se ha recibido con normalidad.",
 "b_caution": "Aún no se ha recibido el aviso previsto para hoy. Le recomendamos comprobarlo directamente.",
 "b_warning": "No se ha recibido el aviso varios días seguidos. Es necesario que lo compruebe directamente.",
 "b_urgent": "Sin aviso desde hace 3 días. Compruébelo de inmediato.",
 "b_sos": "Su ser querido ha pedido ayuda. Compruébelo de inmediato.",
 "view_loc": "🗺️ Ver ubicación",
 "add_title": "Añadir un ser querido",
 "add_guide": "Escriba el código único y un apodo de la persona que quiere añadir.",
 "add_sub": "Una vez conectados, verá cada día su aviso y sus pasos.",
 "add_code_label": "Código único (7 caracteres)",
 "add_alias_label": "Apodo",
 "add_phone_label": "Teléfono (opcional)",
 "add_phone_hint": "612345678",
 "add_connect": "Conectar",
 "add_ok": "Su ser querido ya está conectado.",
 "d1_head": "Personas a su cuidado<br>ahora mismo: 1",
 "d3_head": "Personas a su cuidado<br>ahora mismo: 3",
 "legend_ok": "Todo bien: 2",
 "legend_caution": "Precaución: 1",
 "pill_caution": "⚠️ Precaución",
 "safety_needed": "Compruebe cómo está",
 "call_now": "Llamar ahora",
 "confirm_safety": "Confirmar seguridad",
 "last_1d": "Último aviso: hace 1 día",
 "last_3h": "Último aviso: hace 3 h",
 "map_title": "Ubicación de la emergencia",
 "map_subject": "Ser querido",
 "map_time": "Registrada a las",
 "map_acc": "Precisión"
};
