// 자동 생성(gen_copy.py) — 직접 고치지 말고 marketing.py 를 고친다.
window.S = {
 "brand": "Anbu",
 "push_app": "Anbu",
 "dad": "Papa",
 "p8_lang": "20 langues",
 "p1_h": "Vous vous inquiétez pour vos <em>parents</em><br>qui vivent loin ?",
 "p1_s": "Un enfant qui vit seul vous préoccupe aussi,<br>et appeler chaque jour n’est pas simple.",
 "p2_h": "Ils disent toujours « ça va »,<br>mais est-ce vraiment le cas ?",
 "p2_o": "C’est là qu’Anbu intervient.",
 "p2_s": "Sans appeler, les nouvelles de vos proches<br>arrivent automatiquement chaque jour.",
 "bubble": "Ça va, ne t’inquiète pas~",
 "p3_h": "Sans appeler,<br>des <em>nouvelles</em> chaque jour",
 "p3_s": "Les nouvelles et le nombre de pas arrivent automatiquement.<br>L’expéditeur n’a même pas à ouvrir l’app.",
 "p4_h": "Si le contact se perd,<br>l’alerte vous parvient <em>en premier</em>",
 "p4_s": "Pas de nouvelles : attention → alerte → urgent,<br>étape par étape.",
 "p5_h": "<em>Un seul code</em><br>et c’est connecté",
 "p5_s": "Saisissez le code et le surnom de votre proche<br>pour recevoir ses nouvelles aussitôt.",
 "p6_h": "Les nouvelles de la famille,<br><em>d’un coup d’œil</em>",
 "p6_s": "Jusqu’à 5 personnes sur un seul écran :<br>nouvelles et nombre de pas.",
 "p7_h": "En cas de besoin d’aide,<br>la <em>position</em> suit",
 "p7_s": "Quand votre proche appuie sur « J'ai besoin d'aide », l’aidant est averti aussitôt ; la position n’est partagée qu’à ce moment.",
 "p8_h": "<em>Aucune inscription</em><br>nécessaire",
 "p8_s": "Ni nom ni numéro de téléphone ne sont enregistrés sur le serveur.",
 "p8_chips": [
  "Nom",
  "Téléphone",
  "Adresse"
 ],
 "p8_loc": "Position partagée uniquement sur « J'ai besoin d'aide »",
 "n_title": "Notifications",
 "n_today": "Reçues aujourd'hui",
 "lv_normal": "Normal",
 "lv_caution": "Attention",
 "lv_warning": "Alerte",
 "lv_urgent": "Urgent",
 "b_auto": "Les nouvelles de votre proche sont bien arrivées.",
 "b_caution": "Les nouvelles prévues aujourd'hui ne sont pas encore arrivées. Merci de vérifier vous-même.",
 "b_warning": "Aucune nouvelle plusieurs jours de suite. Une vérification de votre part est nécessaire.",
 "b_urgent": "Aucune nouvelle depuis 3 jours. Veuillez vérifier immédiatement.",
 "b_sos": "Votre proche a demandé de l'aide. Veuillez vérifier immédiatement.",
 "view_loc": "🗺️ Voir la position",
 "add_title": "Ajouter un proche",
 "add_guide": "Saisissez le code unique et un surnom pour le proche à ajouter.",
 "add_sub": "Une fois connecté, vous voyez chaque jour ses nouvelles et son nombre de pas.",
 "add_code_label": "Code unique (7 caractères)",
 "add_alias_label": "Surnom",
 "add_phone_label": "Numéro de téléphone (facultatif)",
 "add_phone_hint": "0612345678",
 "add_connect": "Connecter",
 "add_ok": "Votre proche est connecté.",
 "d1_head": "Proches suivis<br>en ce moment : 1",
 "d3_head": "Proches suivis<br>en ce moment : 3",
 "legend_ok": "Tout va bien : 2",
 "legend_caution": "Attention : 1",
 "pill_caution": "⚠️ Attention",
 "safety_needed": "Vérifiez que tout va bien",
 "call_now": "Appeler",
 "confirm_safety": "Confirmer la sécurité",
 "last_1d": "Dernières nouvelles : il y a 1 jour",
 "last_3h": "Dernières nouvelles : il y a 3 h",
 "map_title": "Position d'urgence",
 "map_subject": "Proche",
 "map_time": "Relevée à",
 "map_acc": "Précision"
};
