// 자동 생성(gen_copy.py) — 직접 고치지 말고 marketing.py 를 고친다.
window.S = {
 "brand": "Anbu",
 "push_app": "Anbu",
 "dad": "Ayah",
 "p8_lang": "20 bahasa",
 "p1_h": "Khawatir pada <em>orang tua</em><br>yang tinggal jauh?",
 "p1_s": "Anak yang tinggal sendiri juga membuat Anda cemas,<br>dan menelepon setiap hari tidak mudah.",
 "p2_h": "Mereka selalu bilang “aku baik-baik saja”,<br>tapi benarkah begitu?",
 "p2_o": "Saat itulah Anda butuh Anbu.",
 "p2_s": "Tanpa perlu menelepon, kabar keluarga Anda<br>datang otomatis setiap hari.",
 "bubble": "Aku baik-baik saja, jangan khawatir~",
 "p3_h": "Tanpa menghubungi,<br><em>kabar</em> tiba setiap hari",
 "p3_s": "Kabar dan jumlah langkah terkirim otomatis.<br>Pengirim bahkan tak perlu membuka aplikasi.",
 "p4_h": "Jika kontak terputus,<br>Anda <em>tahu lebih dulu</em>",
 "p4_s": "Jika kabar tak datang: perhatian → peringatan → mendesak,<br>secara bertahap.",
 "p5_h": "<em>Satu kode</em>,<br>langsung terhubung",
 "p5_s": "Masukkan kode dan nama panggilan orang tersayang Anda,<br>kabarnya langsung Anda terima.",
 "p6_h": "Kabar seluruh keluarga,<br><em>sekali lihat</em>",
 "p6_s": "Hingga 5 orang dalam satu layar:<br>kabar dan jumlah langkah.",
 "p7_h": "Saat butuh bantuan,<br><em>lokasi</em> ikut terkirim",
 "p7_s": "Saat orang tersayang menekan “Saya butuh bantuan”, pendamping langsung diberi tahu; lokasi hanya dibagikan saat itu.",
 "p8_h": "Tak perlu <em>daftar</em><br>akun sama sekali",
 "p8_s": "Nama dan nomor telepon tidak disimpan di server.",
 "p8_chips": [
  "Nama",
  "Nomor telepon",
  "Alamat"
 ],
 "p8_loc": "Lokasi hanya saat menekan “Saya butuh bantuan”",
 "n_title": "Notifikasi",
 "n_today": "Notifikasi hari ini",
 "lv_normal": "Normal",
 "lv_caution": "Perhatian",
 "lv_warning": "Peringatan",
 "lv_urgent": "Mendesak",
 "b_auto": "Kabar dari orang tersayang Anda diterima seperti biasa.",
 "b_caution": "Kabar yang dijadwalkan hari ini belum diterima. Silakan periksa sendiri.",
 "b_warning": "Kabar tidak diterima beberapa hari berturut-turut. Anda perlu memeriksanya sendiri.",
 "b_urgent": "Sudah 3 hari tanpa kabar. Segera periksa.",
 "b_sos": "Orang tersayang Anda meminta bantuan. Segera periksa.",
 "view_loc": "🗺️ Lihat lokasi",
 "add_title": "Tambah orang tersayang",
 "add_guide": "Masukkan kode unik dan nama panggilan orang yang ingin Anda hubungkan.",
 "add_sub": "Setelah terhubung, setiap hari Anda bisa melihat kabar dan jumlah langkahnya.",
 "add_code_label": "Kode unik (7 karakter)",
 "add_alias_label": "Nama panggilan",
 "add_phone_label": "Nomor telepon (opsional)",
 "add_phone_hint": "08123456789",
 "add_connect": "Hubungkan",
 "add_ok": "Orang tersayang Anda sudah terhubung.",
 "d1_head": "Sedang memantau kabar<br>1 orang.",
 "d3_head": "Sedang memantau kabar<br>3 orang.",
 "legend_ok": "Aman: 2",
 "legend_caution": "Perhatian: 1",
 "pill_caution": "⚠️ Perhatian",
 "safety_needed": "Perlu diperiksa",
 "call_now": "Telepon sekarang",
 "confirm_safety": "Konfirmasi aman",
 "last_1d": "Kabar terakhir: 1 hari lalu",
 "last_3h": "Kabar terakhir: 3 jam lalu",
 "map_title": "Lokasi darurat",
 "map_subject": "Orang tersayang",
 "map_time": "Dicatat pukul",
 "map_acc": "Akurasi"
};
