// 자동 생성(gen_copy.py) — 직접 고치지 말고 marketing.py 를 고친다.
window.S = {
 "brand": "Anbu",
 "push_app": "Anbu",
 "dad": "Papà",
 "p8_lang": "20 lingue",
 "p1_h": "È in pensiero per i suoi <em>genitori</em><br>che vivono lontano?",
 "p1_s": "Anche un figlio che vive da solo la preoccupa,<br>e chiamare ogni giorno non è facile.",
 "p2_h": "Dicono sempre «sto bene»,<br>ma sarà proprio così?",
 "p2_o": "È allora che serve Anbu.",
 "p2_s": "Senza che lei chiami, il check-in dei suoi cari<br>arriva ogni giorno in automatico.",
 "bubble": "Sto bene, non preoccuparti~",
 "p3_h": "Anche senza chiamare,<br>il <em>check-in</em> arriva ogni giorno",
 "p3_s": "Check-in e passi arrivano in automatico.<br>Chi li invia non deve nemmeno aprire l’app.",
 "p4_h": "Se il contatto si interrompe,<br>lo sa <em>prima di tutti</em>",
 "p4_s": "Se il check-in non arriva: attenzione → allerta → urgente,<br>passo dopo passo.",
 "p5_h": "<em>Un solo codice</em><br>e siete connessi",
 "p5_s": "Inserisca codice e soprannome della persona cara<br>e riceverà subito i suoi check-in.",
 "p6_h": "Il check-in di tutta la famiglia,<br><em>a colpo d’occhio</em>",
 "p6_s": "Fino a 5 persone su una sola schermata:<br>check-in e passi.",
 "p7_h": "Se serve aiuto,<br>arriva anche la <em>posizione</em>",
 "p7_s": "Quando la persona cara tocca «Ho bisogno di aiuto», il caregiver viene avvisato subito; la posizione è condivisa solo allora.",
 "p8_h": "<em>Nessuna registrazione</em><br>necessaria",
 "p8_s": "Nome e numero di telefono non vengono salvati sul server.",
 "p8_chips": [
  "Nome",
  "Telefono",
  "Indirizzo"
 ],
 "p8_loc": "Posizione solo quando tocca «Ho bisogno di aiuto»",
 "n_title": "Notifiche",
 "n_today": "Ricevute oggi",
 "lv_normal": "Normale",
 "lv_caution": "Attenzione",
 "lv_warning": "Allerta",
 "lv_urgent": "Urgente",
 "b_auto": "Il check-in della persona cara è arrivato regolarmente.",
 "b_caution": "Il check-in previsto per oggi non è ancora arrivato. La invitiamo a verificare direttamente.",
 "b_warning": "Il check-in manca da più giorni consecutivi. È necessario verificare direttamente.",
 "b_urgent": "Nessun check-in da 3 giorni. Verifichi subito.",
 "b_sos": "La persona cara ha chiesto aiuto. Verifichi subito.",
 "view_loc": "🗺️ Vedi posizione",
 "add_title": "Aggiungi una persona cara",
 "add_guide": "Inserisca il codice univoco e un soprannome della persona da collegare.",
 "add_sub": "Una volta collegati, vedrà ogni giorno il suo check-in e i suoi passi.",
 "add_code_label": "Codice univoco (7 caratteri)",
 "add_alias_label": "Soprannome",
 "add_phone_label": "Numero di telefono (facoltativo)",
 "add_phone_hint": "3331234567",
 "add_connect": "Collega",
 "add_ok": "La persona cara è collegata.",
 "d1_head": "Persone che sta seguendo<br>in questo momento: 1",
 "d3_head": "Persone che sta seguendo<br>in questo momento: 3",
 "legend_ok": "Tutto bene: 2",
 "legend_caution": "Attenzione: 1",
 "pill_caution": "⚠️ Attenzione",
 "safety_needed": "Verifichi come sta",
 "call_now": "Chiama ora",
 "confirm_safety": "Conferma sicurezza",
 "last_1d": "Ultimo check-in: 1 giorno fa",
 "last_3h": "Ultimo check-in: 3 h fa",
 "map_title": "Posizione dell'emergenza",
 "map_subject": "Persona cara",
 "map_time": "Rilevata alle",
 "map_acc": "Precisione"
};
