// 자동 생성(gen_copy.py) — 직접 고치지 말고 marketing.py 를 고친다.
window.S = {
 "brand": "Anbu",
 "push_app": "Anbu",
 "dad": "Papa",
 "p8_lang": "20 talen",
 "p1_h": "Maakt u zich zorgen om uw <em>ouders</em><br>die ver weg wonen?",
 "p1_s": "Ook een kind dat alleen woont houdt u bezig,<br>en elke dag bellen is niet makkelijk.",
 "p2_h": "Ze zeggen altijd “het gaat goed”,<br>maar is dat echt zo?",
 "p2_o": "Dan is er Anbu.",
 "p2_s": "Zonder dat u belt, komt de check-in van uw familie<br>elke dag automatisch binnen.",
 "bubble": "Het gaat goed, geen zorgen~",
 "p3_h": "Zonder te bellen<br>komt de <em>check-in</em> elke dag",
 "p3_s": "Check-in en stappen komen automatisch binnen.<br>De afzender hoeft de app niet eens te openen.",
 "p4_h": "Valt het contact weg,<br>dan weet u het <em>als eerste</em>",
 "p4_s": "Geen check-in? Let op → waarschuwing → dringend,<br>stap voor stap.",
 "p5_h": "<em>Eén code</em><br>en u bent verbonden",
 "p5_s": "Voer de code en bijnaam van uw naaste in<br>en ontvang meteen hun check-in.",
 "p6_h": "De check-in van uw hele familie,<br><em>in één oogopslag</em>",
 "p6_s": "Tot 5 personen op één scherm:<br>check-in en stappen.",
 "p7_h": "Is er hulp nodig,<br>dan gaat de <em>locatie</em> mee",
 "p7_s": "Tikt uw naaste op “Ik heb hulp nodig”, dan krijgt de contactpersoon direct bericht; de locatie wordt alleen dan gedeeld.",
 "p8_h": "Zelfs <em>registreren</em><br>hoeft niet",
 "p8_s": "Naam en telefoonnummer worden niet op de server opgeslagen.",
 "p8_chips": [
  "Naam",
  "Telefoonnummer",
  "Adres"
 ],
 "p8_loc": "Locatie alleen bij “Ik heb hulp nodig”",
 "n_title": "Meldingen",
 "n_today": "Vandaag ontvangen",
 "lv_normal": "Normaal",
 "lv_caution": "Let op",
 "lv_warning": "Waarschuwing",
 "lv_urgent": "Dringend",
 "b_auto": "De check-in van uw naaste is zoals gewoonlijk ontvangen.",
 "b_caution": "De geplande check-in van vandaag is nog niet ontvangen. Ga zelf even na of alles goed is.",
 "b_warning": "Er is meerdere dagen achter elkaar geen check-in ontvangen. Ga zelf na of alles goed is.",
 "b_urgent": "Al 3 dagen geen check-in. Ga direct na of alles goed is.",
 "b_sos": "Uw naaste heeft om hulp gevraagd. Ga direct na of alles goed is.",
 "view_loc": "🗺️ Locatie bekijken",
 "add_title": "Naaste toevoegen",
 "add_guide": "Voer de unieke code en een bijnaam in van de persoon die u wilt verbinden.",
 "add_sub": "Na het verbinden ziet u elke dag de check-in en het aantal stappen.",
 "add_code_label": "Unieke code (7 tekens)",
 "add_alias_label": "Bijnaam",
 "add_phone_label": "Telefoonnummer (optioneel)",
 "add_phone_hint": "0612345678",
 "add_connect": "Verbinden",
 "add_ok": "Uw naaste is verbonden.",
 "d1_head": "Naasten die u<br>nu volgt: 1",
 "d3_head": "Naasten die u<br>nu volgt: 3",
 "legend_ok": "Alles goed: 2",
 "legend_caution": "Let op: 1",
 "pill_caution": "⚠️ Let op",
 "safety_needed": "Ga na of alles goed is",
 "call_now": "Nu bellen",
 "confirm_safety": "Veiligheid bevestigen",
 "last_1d": "Laatste check-in: 1 dag geleden",
 "last_3h": "Laatste check-in: 3 uur geleden",
 "map_title": "Locatie van de noodmelding",
 "map_subject": "Naaste",
 "map_time": "Vastgelegd om",
 "map_acc": "Nauwkeurigheid"
};
