// 자동 생성(gen_copy.py) — 직접 고치지 말고 marketing.py 를 고친다.
window.S = {
 "brand": "Anbu",
 "push_app": "Anbu",
 "dad": "Tata",
 "p8_lang": "20 języków",
 "p1_h": "Martwisz się o <em>rodziców</em>,<br>którzy mieszkają daleko?",
 "p1_s": "Niepokoi Cię też dziecko mieszkające samo,<br>a dzwonienie codziennie nie jest łatwe.",
 "p2_h": "Zawsze mówią „wszystko dobrze”,<br>ale czy na pewno?",
 "p2_o": "Wtedy przydaje się Anbu.",
 "p2_s": "Nawet jeśli nie dzwonisz, znak życia bliskich<br>przychodzi automatycznie każdego dnia.",
 "bubble": "Wszystko dobrze, nie martw się~",
 "p3_h": "Bez dzwonienia<br><em>znak życia</em> przychodzi codziennie",
 "p3_s": "Znak życia i kroki docierają automatycznie.<br>Wysyłający nie musi nawet otwierać aplikacji.",
 "p4_h": "Gdy kontakt się urwie,<br>dowiesz się <em>przed wszystkimi</em>",
 "p4_s": "Brak znaku życia: uwaga → ostrzeżenie → pilne,<br>krok po kroku.",
 "p5_h": "<em>Jeden kod</em><br>i gotowe połączenie",
 "p5_s": "Wpisz kod i pseudonim podopiecznego,<br>a od razu zaczniesz otrzymywać jego znaki życia.",
 "p6_h": "Znaki życia całej rodziny<br><em>na jednym ekranie</em>",
 "p6_s": "Do 5 osób na jednym ekranie:<br>znaki życia i kroki.",
 "p7_h": "Gdy potrzebna jest pomoc,<br><em>lokalizacja</em> idzie razem",
 "p7_s": "Gdy podopieczny naciśnie „Potrzebuję pomocy”, opiekun dostaje powiadomienie od razu, a lokalizacja jest udostępniana tylko wtedy.",
 "p8_h": "<em>Rejestracja</em><br>nie jest potrzebna",
 "p8_s": "Imię i numer telefonu nie są zapisywane na serwerze.",
 "p8_chips": [
  "Imię",
  "Telefon",
  "Adres"
 ],
 "p8_loc": "Lokalizacja tylko po naciśnięciu „Potrzebuję pomocy”",
 "n_title": "Powiadomienia",
 "n_today": "Dzisiejsze",
 "lv_normal": "W normie",
 "lv_caution": "Uwaga",
 "lv_warning": "Ostrzeżenie",
 "lv_urgent": "Pilne",
 "b_auto": "Znak życia od podopiecznego dotarł jak zwykle.",
 "b_caution": "Zaplanowany na dziś znak życia jeszcze nie dotarł. Sprawdź to bezpośrednio.",
 "b_warning": "Kolejny dzień z rzędu aplikacja Anbu nie otrzymała znaku życia. Sprawdź to bezpośrednio.",
 "b_urgent": "Od 3 dni aplikacja Anbu nie otrzymała znaku życia. Sprawdź natychmiast.",
 "b_sos": "Podopieczny poprosił o pomoc. Sprawdź natychmiast.",
 "view_loc": "🗺️ Pokaż lokalizację",
 "add_title": "Dodaj podopiecznego",
 "add_guide": "Wpisz unikalny kod i nazwę osoby, którą chcesz połączyć.",
 "add_sub": "Po połączeniu codziennie zobaczysz jej znak życia i liczbę kroków.",
 "add_code_label": "Unikalny kod (7 znaków)",
 "add_alias_label": "Nazwa podopiecznego",
 "add_phone_label": "Numer telefonu (opcjonalnie)",
 "add_phone_hint": "512345678",
 "add_connect": "Połącz",
 "add_ok": "Podopieczny został połączony.",
 "d1_head": "Podopieczni<br>pod opieką: 1",
 "d3_head": "Podopieczni<br>pod opieką: 3",
 "legend_ok": "W porządku: 2",
 "legend_caution": "Uwaga: 1",
 "pill_caution": "⚠️ Uwaga",
 "safety_needed": "Trzeba sprawdzić",
 "call_now": "Zadzwoń",
 "confirm_safety": "Potwierdź bezpieczeństwo",
 "last_1d": "Ostatni znak życia: 1 dn. temu",
 "last_3h": "Ostatni znak życia: 3 godz. temu",
 "map_title": "Lokalizacja wezwania",
 "map_subject": "Podopieczny",
 "map_time": "Ustalona o",
 "map_acc": "Dokładność"
};
