// 자동 생성(gen_copy.py) — 직접 고치지 말고 marketing.py 를 고친다.
window.S = {
 "brand": "Anbu",
 "push_app": "Anbu",
 "dad": "Pai",
 "p8_lang": "20 idiomas",
 "p1_h": "Você se preocupa com seus <em>pais</em><br>que moram longe?",
 "p1_s": "Um filho que mora sozinho também pesa no coração,<br>e ligar todo dia não é fácil.",
 "p2_h": "Eles sempre dizem “estou bem”,<br>mas será que estão mesmo?",
 "p2_o": "É aí que o Anbu entra.",
 "p2_s": "Sem você precisar ligar, o check-in da sua família<br>chega automaticamente todo dia.",
 "bubble": "Estou bem, não se preocupe~",
 "p3_h": "Sem precisar ligar,<br>o <em>check-in</em> chega todo dia",
 "p3_s": "Check-in e passos chegam automaticamente.<br>Quem envia nem precisa abrir o app.",
 "p4_h": "Se o contato for interrompido,<br>você sabe <em>antes de todo mundo</em>",
 "p4_s": "Sem check-in: atenção → alerta → urgente,<br>etapa por etapa.",
 "p5_h": "<em>Um código</em><br>e pronto, conectado",
 "p5_s": "Digite o código e o apelido do seu ente querido<br>e receba os check-ins na hora.",
 "p6_h": "O check-in da família toda,<br><em>num relance</em>",
 "p6_s": "Até 5 pessoas em uma só tela:<br>check-in e passos.",
 "p7_h": "Se precisar de ajuda,<br>a <em>localização</em> vai junto",
 "p7_s": "Quando seu ente querido toca em “Preciso de ajuda”, o cuidador é avisado na hora; a localização só é compartilhada nesse momento.",
 "p8_h": "<em>Sem cadastro</em><br>nenhum",
 "p8_s": "Nome e telefone não são guardados no servidor.",
 "p8_chips": [
  "Nome",
  "Telefone",
  "Endereço"
 ],
 "p8_loc": "Localização só ao tocar em “Preciso de ajuda”",
 "n_title": "Notificações",
 "n_today": "Recebidas hoje",
 "lv_normal": "Normal",
 "lv_caution": "Atenção",
 "lv_warning": "Alerta",
 "lv_urgent": "Urgente",
 "b_auto": "O check-in do seu ente querido chegou normalmente.",
 "b_caution": "O check-in previsto para hoje ainda não chegou. Recomendamos verificar diretamente.",
 "b_warning": "O check-in não chega há vários dias seguidos. É preciso verificar diretamente.",
 "b_urgent": "Sem check-in há 3 dias. Verifique imediatamente.",
 "b_sos": "Seu ente querido pediu ajuda. Verifique imediatamente.",
 "view_loc": "🗺️ Ver localização",
 "add_title": "Adicionar ente querido",
 "add_guide": "Digite o código único e um apelido da pessoa que você quer conectar.",
 "add_sub": "Depois de conectar, você vê todo dia o check-in e os passos dessa pessoa.",
 "add_code_label": "Código único (7 caracteres)",
 "add_alias_label": "Apelido",
 "add_phone_label": "Telefone (opcional)",
 "add_phone_hint": "11961234567",
 "add_connect": "Conectar",
 "add_ok": "Seu ente querido foi conectado.",
 "d1_head": "Pessoas que você<br>acompanha agora: 1",
 "d3_head": "Pessoas que você<br>acompanha agora: 3",
 "legend_ok": "Tudo bem: 2",
 "legend_caution": "Atenção: 1",
 "pill_caution": "⚠️ Atenção",
 "safety_needed": "Confira se está tudo bem",
 "call_now": "Ligar agora",
 "confirm_safety": "Confirmar segurança",
 "last_1d": "Último check-in: há 1 dia",
 "last_3h": "Último check-in: há 3 h",
 "map_title": "Local da emergência",
 "map_subject": "Ente querido",
 "map_time": "Registrada às",
 "map_acc": "Precisão"
};
