// 자동 생성(gen_copy.py) — 직접 고치지 말고 marketing.py 를 고친다.
window.S = {
 "brand": "Anbu",
 "push_app": "Anbu",
 "dad": "Pappa",
 "p8_lang": "20 språk",
 "p1_h": "Oroar du dig för dina <em>föräldrar</em><br>som bor långt bort?",
 "p1_s": "Även ett barn som bor ensamt ligger på hjärtat,<br>och att ringa varje dag är inte lätt.",
 "p2_h": "De säger alltid ”det är bra”,<br>men är det verkligen det?",
 "p2_o": "Då behövs Anbu.",
 "p2_s": "Utan att du ringer kommer familjens incheckning<br>automatiskt varje dag.",
 "bubble": "Det är bra, oroa dig inte~",
 "p3_h": "Utan att ringa<br>kommer <em>incheckningen</em> varje dag",
 "p3_s": "Incheckning och steg kommer automatiskt.<br>Den som skickar behöver inte ens öppna appen.",
 "p4_h": "Om kontakten bryts<br>får du veta det <em>först</em>",
 "p4_s": "Uteblir incheckningen: observera → varning → brådskande,<br>steg för steg.",
 "p5_h": "<em>En kod</em><br>och ni är anslutna",
 "p5_s": "Ange din närståendes kod och smeknamn<br>så får du incheckningarna direkt.",
 "p6_h": "Hela familjens incheckning<br><em>på en gång</em>",
 "p6_s": "Upp till 5 personer på en skärm:<br>incheckning och steg.",
 "p7_h": "När hjälp behövs<br>följer <em>platsen</em> med",
 "p7_s": "När din närstående trycker på ”Jag behöver hjälp” får kontaktpersonen besked direkt – platsen delas bara då.",
 "p8_h": "Ingen <em>registrering</em><br>behövs",
 "p8_s": "Namn och telefonnummer sparas inte på servern.",
 "p8_chips": [
  "Namn",
  "Telefonnummer",
  "Adress"
 ],
 "p8_loc": "Plats delas bara vid ”Jag behöver hjälp”",
 "n_title": "Aviseringar",
 "n_today": "Mottagna i dag",
 "lv_normal": "Normal",
 "lv_caution": "Observera",
 "lv_warning": "Varning",
 "lv_urgent": "Brådskande",
 "b_auto": "Din närståendes incheckning har kommit in som vanligt.",
 "b_caution": "Dagens planerade incheckning har inte kommit in än. Kontrollera själv hur det står till.",
 "b_warning": "Incheckningen har uteblivit flera dagar i rad. Kontrollera själv hur det står till.",
 "b_urgent": "Ingen incheckning på 3 dagar. Kontrollera omedelbart.",
 "b_sos": "Din närstående har bett om hjälp. Kontrollera omedelbart.",
 "view_loc": "🗺️ Visa plats",
 "add_title": "Lägg till närstående",
 "add_guide": "Ange den unika koden och ett smeknamn för personen du vill koppla ihop dig med.",
 "add_sub": "När ni är ihopkopplade ser du varje dag personens incheckning och antal steg.",
 "add_code_label": "Unik kod (7 tecken)",
 "add_alias_label": "Smeknamn",
 "add_phone_label": "Telefonnummer (valfritt)",
 "add_phone_hint": "0701234567",
 "add_connect": "Koppla ihop",
 "add_ok": "Din närstående är nu ansluten.",
 "d1_head": "Närstående du<br>håller koll på: 1",
 "d3_head": "Närstående du<br>håller koll på: 3",
 "legend_ok": "Allt bra: 2",
 "legend_caution": "Observera: 1",
 "pill_caution": "⚠️ Observera",
 "safety_needed": "Behöver kontrolleras",
 "call_now": "Ring nu",
 "confirm_safety": "Bekräfta säkerhet",
 "last_1d": "Senaste incheckning: för 1 dag sedan",
 "last_3h": "Senaste incheckning: för 3 tim sedan",
 "map_title": "Plats vid nödsituation",
 "map_subject": "Närstående",
 "map_time": "Registrerad kl.",
 "map_acc": "Noggrannhet"
};
