// 자동 생성(gen_copy.py) — 직접 고치지 말고 marketing.py 를 고친다.
window.S = {
 "brand": "Anbu",
 "push_app": "Anbu",
 "dad": "Baba",
 "p8_lang": "20 dil",
 "p1_h": "Uzaktaki <em>anne babanız</em> için<br>endişeleniyor musunuz?",
 "p1_s": "Tek başına yaşayan çocuğunuz da aklınızda,<br>her gün aramak ise kolay değil.",
 "p2_h": "Hep “iyiyim” derler,<br>peki gerçekten iyiler mi?",
 "p2_o": "İşte o zaman Anbu gerekir.",
 "p2_s": "Siz aramasanız da ailenizden gelen haber<br>her gün otomatik olarak ulaşır.",
 "bubble": "İyiyim, merak etme~",
 "p3_h": "Aramasanız da<br>her gün <em>haber</em> gelir",
 "p3_s": "Haber ve adım sayısı otomatik gelir.<br>Gönderenin uygulamayı açması bile gerekmez.",
 "p4_h": "İletişim kesilirse<br><em>ilk siz</em> haberdar olursunuz",
 "p4_s": "Haber gelmezse: dikkat → uyarı → acil,<br>adım adım bildirilir.",
 "p5_h": "<em>Tek bir kod</em>,<br>bağlantı tamam",
 "p5_s": "Yakınınızın kodunu ve takma adını girin,<br>haberlerini hemen almaya başlayın.",
 "p6_h": "Ailenizin haberi<br><em>tek bakışta</em>",
 "p6_s": "Tek ekranda en fazla 5 kişi:<br>haber ve adım sayısı.",
 "p7_h": "Yardım gerektiğinde<br><em>konum</em> da gelir",
 "p7_s": "Yakınınız “Yardıma ihtiyacım var” düğmesine dokununca koruyucuya hemen bildirim gider; konum yalnızca o anda paylaşılır.",
 "p8_h": "<em>Üyelik</em> bile<br>gerekmez",
 "p8_s": "Ad ve telefon numarası sunucuda saklanmaz.",
 "p8_chips": [
  "Ad",
  "Telefon numarası",
  "Adres"
 ],
 "p8_loc": "Konum yalnızca “Yardıma ihtiyacım var” düğmesine dokunulduğunda",
 "n_title": "Bildirimler",
 "n_today": "Bugün gelenler",
 "lv_normal": "Normal",
 "lv_caution": "Dikkat",
 "lv_warning": "Uyarı",
 "lv_urgent": "Acil",
 "b_auto": "Yakınınızdan her zamanki gibi haber alındı.",
 "b_caution": "Bugün planlanan saatte beklenen haber henüz gelmedi. Lütfen kendiniz kontrol edin.",
 "b_warning": "Art arda birkaç gündür haber alınamıyor. Kendiniz kontrol etmeniz gerekiyor.",
 "b_urgent": "3 gündür haber alınamadı. Lütfen hemen kontrol edin.",
 "b_sos": "Yakınınız yardım istedi. Lütfen hemen kontrol edin.",
 "view_loc": "🗺️ Konumu göster",
 "add_title": "Yakın ekle",
 "add_guide": "Bağlanmak istediğiniz kişinin benzersiz kodunu ve bir takma ad girin.",
 "add_sub": "Bağlandıktan sonra her gün o kişiden gelen haberi ve adım sayısını görebilirsiniz.",
 "add_code_label": "Benzersiz kod (7 karakter)",
 "add_alias_label": "Takma ad",
 "add_phone_label": "Telefon numarası (isteğe bağlı)",
 "add_phone_hint": "05321234567",
 "add_connect": "Bağlan",
 "add_ok": "Yakınınız bağlandı.",
 "d1_head": "Şu an takip ettiğiniz<br>kişi sayısı: 1",
 "d3_head": "Şu an takip ettiğiniz<br>kişi sayısı: 3",
 "legend_ok": "Güvende: 2",
 "legend_caution": "Dikkat: 1",
 "pill_caution": "⚠️ Dikkat",
 "safety_needed": "Kontrol gerekli",
 "call_now": "Hemen ara",
 "confirm_safety": "Güvende olduğunu onayla",
 "last_1d": "Son haber: 1 gün önce",
 "last_3h": "Son haber: 3 sa önce",
 "map_title": "Acil durum konumu",
 "map_subject": "Yakın",
 "map_time": "Alındığı saat",
 "map_acc": "Doğruluk"
};
