// 자동 생성(gen_copy.py) — 직접 고치지 말고 marketing.py 를 고친다.
window.S = {
 "brand": "Anbu",
 "push_app": "Anbu",
 "dad": "Bố",
 "p8_lang": "20 ngôn ngữ",
 "p1_h": "Bạn lo cho <em>cha mẹ</em><br>ở xa?",
 "p1_s": "Con cái sống một mình cũng khiến bạn lo,<br>mà ngày nào cũng gọi điện thì không dễ.",
 "p2_h": "Họ luôn nói “tôi ổn”,<br>nhưng liệu có thật sự ổn?",
 "p2_o": "Khi đó, bạn cần Anbu.",
 "p2_s": "Không cần gọi, tin bình an của người thân<br>tự động đến mỗi ngày.",
 "bubble": "Ổn mà, đừng lo nhé~",
 "p3_h": "Không cần liên lạc,<br><em>tin bình an</em> vẫn đến mỗi ngày",
 "p3_s": "Tin bình an và số bước chân tự động gửi đến.<br>Người gửi thậm chí không cần mở ứng dụng.",
 "p4_h": "Khi liên lạc bị gián đoạn,<br>bạn biết <em>đầu tiên</em>",
 "p4_s": "Không có tin bình an: chú ý → cảnh báo → khẩn cấp,<br>từng bước một.",
 "p5_h": "<em>Một mã</em><br>là kết nối xong",
 "p5_s": "Nhập mã và biệt danh của người thân<br>là nhận được tin bình an ngay.",
 "p6_h": "Tin bình an cả nhà,<br><em>nhìn là biết</em>",
 "p6_s": "Tối đa 5 người trên một màn hình:<br>tin bình an và số bước chân.",
 "p7_h": "Khi cần giúp đỡ,<br>kèm cả <em>vị trí</em>",
 "p7_s": "Khi người thân nhấn “Tôi cần giúp đỡ”, người chăm sóc được báo ngay; vị trí chỉ được chia sẻ vào lúc đó.",
 "p8_h": "Không cần cả<br><em>đăng ký</em>",
 "p8_s": "Tên và số điện thoại không được lưu trên máy chủ.",
 "p8_chips": [
  "Tên",
  "Số điện thoại",
  "Địa chỉ"
 ],
 "p8_loc": "Vị trí chỉ khi nhấn “Tôi cần giúp đỡ”",
 "n_title": "Thông báo",
 "n_today": "Thông báo hôm nay",
 "lv_normal": "Bình thường",
 "lv_caution": "Chú ý",
 "lv_warning": "Cảnh báo",
 "lv_urgent": "Khẩn cấp",
 "b_auto": "Đã nhận tin bình an của người thân bạn như thường lệ.",
 "b_caution": "Tin bình an theo lịch hôm nay vẫn chưa đến. Vui lòng tự kiểm tra trực tiếp.",
 "b_warning": "Đã nhiều ngày liên tiếp không nhận được tin bình an. Bạn cần tự kiểm tra trực tiếp.",
 "b_urgent": "Đã 3 ngày không có tin bình an. Vui lòng kiểm tra ngay.",
 "b_sos": "Người thân của bạn đã yêu cầu trợ giúp. Vui lòng kiểm tra ngay.",
 "view_loc": "🗺️ Xem vị trí",
 "add_title": "Thêm người thân",
 "add_guide": "Nhập mã riêng và tên gọi của người bạn muốn kết nối.",
 "add_sub": "Sau khi kết nối, mỗi ngày bạn sẽ thấy tin bình an và số bước của người đó.",
 "add_code_label": "Mã riêng (7 ký tự)",
 "add_alias_label": "Tên gọi",
 "add_phone_label": "Số điện thoại (không bắt buộc)",
 "add_phone_hint": "0912345678",
 "add_connect": "Kết nối",
 "add_ok": "Đã kết nối người thân.",
 "d1_head": "Đang theo dõi bình an<br>của 1 người.",
 "d3_head": "Đang theo dõi bình an<br>của 3 người.",
 "legend_ok": "Bình an: 2",
 "legend_caution": "Chú ý: 1",
 "pill_caution": "⚠️ Chú ý",
 "safety_needed": "Cần kiểm tra",
 "call_now": "Gọi ngay",
 "confirm_safety": "Xác nhận an toàn",
 "last_1d": "Lần cuối: 1 ngày trước",
 "last_3h": "Lần cuối: 3 giờ trước",
 "map_title": "Vị trí khẩn cấp",
 "map_subject": "Người thân",
 "map_time": "Ghi nhận lúc",
 "map_acc": "Độ chính xác"
};
