// 자동 생성(gen_feature.py) — 직접 고치지 말 것
window.F = {
 "bcp": "ja",
 "dir": "ltr",
 "appbar": "Anbu 見守り",
 "phead": "現在2人の安否を<br>見守っています。",
 "psum": "今日の安否まとめ",
 "lg_ok": "安全：1",
 "lg_caution": "注意：1",
 "plist": "見守られる方の一覧",
 "mom": "母",
 "dad": "父",
 "pill_ok": "✅ 安全",
 "pill_caution": "注意",
 "act": "活動量：活発",
 "steps": "歩数",
 "last7": "過去7日",
 "peak": "6,240",
 "last": "最終確認：2時間前",
 "warn": "安全確認が必要です",
 "call": "今すぐ電話",
 "confirm": "安全確認済み",
 "add": "見守られる方を追加",
 "now": "今",
 "nav": [
  "ホーム",
  "接続",
  "通知",
  "設定"
 ],
 "push_title": "✅ 本日の安否確認完了",
 "co_copy": "安全コードをコピー",
 "co_share": "安全コードをSNSで共有",
 "co_copy_sm": "コピー",
 "co_share_sm": "共有",
 "push_body": "母 · 本日の歩数は6,240歩です。"
};
